// Generated by Sideko (sideko.dev)
import * as fs from "fs";
import axios, { AxiosInstance, ResponseType, AxiosRequestConfig } from "axios";
import * as FormData from "form-data";

import {  UploadFile,  Item,  GetUpdatesJsonResponse,  User,  }  from "./schemas";
import {  GetAskstoriesJsonRequest,  GetBeststoriesJsonRequest,  GetItemIdJsonRequest,  GetJobstoriesJsonRequest,  GetMaxitemJsonRequest,  GetNewstoriesJsonRequest,  GetShowstoriesJsonRequest,  GetTopstoriesJsonRequest,  GetUpdatesJsonRequest,  GetUserIdJsonRequest,  } from "./request_types"

export default class Client {
    public instance: AxiosInstance;
    private auth: Record<
        string,
        ((axCfg: AxiosRequestConfig) => AxiosRequestConfig) | undefined
    >;

    constructor(config?: { baseUrl?: string }) {
        this.instance = axios.create({
            baseURL: config?.baseUrl ?? "https://hacker-news.firebaseio.com/v0",
            timeout: 1000,
        });
        // register auth providers
        this.auth = {};
    }

    authedAxiosConfig(
        authNames: string[],
        axiosConfig: AxiosRequestConfig
    ): AxiosRequestConfig {
        for (const authName of authNames) {
            const provider = this.auth[authName];
            if (provider) {
                axiosConfig = provider(axiosConfig);
            }
        }

        return axiosConfig;
    }

    public async getAskStoryIds(request: GetAskstoriesJsonRequest): Promise<number[]> {
        // List the latest Ask HN story IDs. Will return maximum 200 IDs. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/askstories.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as number[];
    }

    public async getBestStoryIds(request: GetBeststoriesJsonRequest): Promise<number[]> {
        // List the best hacker news story IDs. Will return maximum 500 IDs. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/beststories.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as number[];
    }

    public async getItem(request: GetItemIdJsonRequest): Promise<Item> {
        // Stories, Comments, Jobs, Ask HNs and even Polls are all considered items, with slightly different structures (see the examples). -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/item/${request.id}.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as Item;
    }

    public async getJobStoryIds(request: GetJobstoriesJsonRequest): Promise<number[]> {
        // List the latest Job story IDs. Will return maximum 200 IDs. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/jobstories.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as number[];
    }

    public async getMaxItemId(request: GetMaxitemJsonRequest): Promise<number> {
        // The current largest item ID. Walking backwards from here allows you to list all items avialable through the API. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/maxitem.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as number;
    }

    public async getNewStoryIds(request: GetNewstoriesJsonRequest): Promise<number[]> {
        // List the top hacker news story IDs. Will return maximum 500 IDs. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/newstories.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as number[];
    }

    public async getShowStoryIds(request: GetShowstoriesJsonRequest): Promise<number[]> {
        // List the latest Show HN story IDs. Will return maximum 200 IDs. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/showstories.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as number[];
    }

    public async getTopStoryIds(request: GetTopstoriesJsonRequest): Promise<number[]> {
        // List the top hacker news story IDs. Will return maximum 500 IDs. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/topstories.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as number[];
    }

    public async getUpdates(request: GetUpdatesJsonRequest): Promise<GetUpdatesJsonResponse> {
        // List recently updated item IDs and profile IDs. -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/updates.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as GetUpdatesJsonResponse;
    }

    public async getUser(request: GetUserIdJsonRequest): Promise<User> {
        // Retrieves user metadata given the user ID (HN username). -  - *Documentation &amp; SDKs generated by Sideko from OpenAPI. Install and try the free beta SDK generator on our [Github](https://github.com/Sideko-Inc/sideko).* - 
        const axiosConfig = {
            method: "GET",
            url: `/user/${request.id}.json`,
            params: {},
            headers: {},
        };
        axiosConfig.params["print"] = request.print;

        const authedConfig = this.authedAxiosConfig(
            [],
            axiosConfig
        )
        const response = await this.instance.request(authedConfig);

        return response.data as User;
    }

}

