// Generated by Sideko (sideko.dev)
import {
  UploadFile,
  Item,
  GetUpdatesJsonResponse,
  User
} from "./schemas";

export type GetAskstoriesJsonRequest = {
  "print"?: string
}

export type GetBeststoriesJsonRequest = {
  "print"?: string
}

export type GetItemIdJsonRequest = {
  "id": number
  "print"?: string
}

export type GetJobstoriesJsonRequest = {
  "print"?: string
}

export type GetMaxitemJsonRequest = {
  "print"?: string
}

export type GetNewstoriesJsonRequest = {
  "print"?: string
}

export type GetShowstoriesJsonRequest = {
  "print"?: string
}

export type GetTopstoriesJsonRequest = {
  "print"?: string
}

export type GetUpdatesJsonRequest = {
  "print"?: string
}

export type GetUserIdJsonRequest = {
  "id": string
  "print"?: string
}
